project:
  type: website
  output-dir: _site

website:
  title: "Gaia Lens Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

listing:
  contents: posts
  sort: "date desc"
  type: default
